#!/bin/bash
# REV03: Fri Jun 29 02:12:26 WIB 2018
# REV02: Mon Feb 26 21:08:14 WIB 2018
# START: Tue Jan 30 19:50:17 WIB 2018

# R: Just run "bash a01-README"

# Copyright (C) 2018 Rahmat M. Samik-Ibrahim et.al.
# http://RahmatM.Samik-Ibrahim.vLSM.org/
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

XX="xx"
HEAD="a"

PREFIX="^#.R:"
RESULT=`grep $PREFIX $0`
clear
if [[ $RESULT ]] ; then
   printf "\n[%11s]: %s\n" "`cut -c 1-11 <<< $0`" "$RESULT"
fi
echo ""; 
echo "This screen size should be at least \"80 x 23\" characters..."
echo "RESIZE the screen if this following message does not fit in \"80 x 23\""
echo ""; echo "*** Hit Enter Key ***";
[ "$1" = "$XX" ] || (read YY)

cat - << NNNN
01 START START START START START START START START START START START START START
12345678911234567892123456789312345678941234567895123456789612345678971234567898
         10        20        30        40        50        60        70       79

12345678911234567892123456789312345678941234567895123456789612345678971234567898

         10        20        30        40        50        60        70       79
12345678911234567892123456789312345678941234567895123456789612345678971234567898
09 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXX                           TEST FOR 80 x 23                           XXXXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
12345678911234567892123456789312345678941234567895123456789612345678971234567898
         10        20        30        40        50        60        70       79

         10        20        30        40        50        60        70       79
12345678911234567892123456789312345678941234567895123456789612345678971234567898
19 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

         10        20        30        40        50        60        70       79
12345678911234567892123456789312345678941234567895123456789612345678971234567898
23 END END END END END END END END END  ====   H I T   E N T E R   K E Y   =====
NNNN

[ "$1" = "$XX" ] || (read YY)
echo ""; echo "Directory listing (running \"ls -AF\"):"
echo "================================================================================"
ls -AF
echo "================================================================================"

[ "$1" = "$XX" ] || (read YY)

cat - << NNNN
================================================================================
This is a README file for this demo.

Rahmat M. Samik-Ibrahim
================================================================================
NNNN

[ "$1" = "$XX" ] || (read YY)

echo ""; echo "[-----------]: # R: LISTING THE LINES ========  ==  ==  ==  ==  ==  ==  ========"
for II in ${HEAD}* ; do
   RESULT=`grep $PREFIX $II`
   if [[ $RESULT ]] ; then
      printf "[%11s]: %s\n" "`cut -c 1-11 <<< $II`" "$RESULT"
   fi
done

exit

# 34567891123456789212345678931234567894123456789512345678961234567897
# Fri Jun 29 02:13:46 WIB 2018

# Apa yang dijalankan script ini adalah mengecek ukuran dari layar 
# terminal apakah sesuai
# Ukuran yang diharapkan adalah 80 x 23, jika tidak begitu output yang 
# dihasilkan akan terlihat berantakan atau ada longgar lalu script ini 
# juga menunjukkan berkas-berkas yang ada dalam folder Week01 
# (dengan perintah ls -AF)

# ----------------------------------------
# Notes By RPS (WK14)
# Line 16
# Variabel bernama PREFIX beisi regex sebagai berikut: ^#.R:
# Artinya: semua line yang dimulai dengan karakter #(apapun)R:'

# Line 17
# Variabel RESULT berisi command: grep $PREFIX $0
# Artinya: ambil/grep baris dari file ini ($0) yang sesuai dengan 
# format regex pada variabel $PREFIX

# Line 20
# Program melakukan printf dengan format berikut:
# \n[%11s]: %s \n artinya: (new line) [(11 digit dari parameter 1)]: 
# (string parameter 2)(new line)
# Parameter 1 berisi cut -c 1-11 <<< $0 artinya: 
#             lakukan cut karakter 1-11 dari nama file ini ($0)
# Parameter 2 $RESULT berisi output dari command grep yang ada 
#             di dalam variabel RESULT

# Line 73
# For II in ${HEAD}* artinya: Lakukan for loop untuk setiap file 
# dengan awalan a
# (a adalah isi dari variabel $HEAD)

# Line 76
# Sama dengan penjelasan Line 20 namun input dari command cut adalah
# file-file yang masuk dalam kondisi for loop (file berawalan a)

# Line 73-77 akan menampilkan judul file-file dalam directory 
#       Week01 (11 karakter) dan baris berawalan # R: dari 
#       masing-masing file
# -------------------------------------------

