#!/bin/bash
# REV04: Mon Feb 12 19:49:54 WIB 2018
# START: Mon Sep  5 14:25:10 WIB 2016

# R: Finding "EXISTS". Just run "bash a05-finding-EXIST"

# Copyright (C) 2016-2018 http://RahmatM.Samik-Ibrahim.vLSM.org/
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


PREFIX="^#.R:"
RESULT=`grep $PREFIX $0`
clear
if [[ $RESULT ]] ; then
   printf "\n[%11s]: %s\n" "`cut -c 1-11 <<< $0`" "$RESULT"
fi
echo ""; 
echo "File list:"
echo "=========="

for file in `ls a[01]*`
do
   echo -n $file
   if grep -q EXIST $file
      then
      echo -n " YES *******"
   fi
   echo ""
	
done

exit 0

/*created by zhelialifa WK5
*Run with Ubuntu Container
*Line 14: variable RESULT akan menampung setiap nama file yang ada di 
*dalam folder W01-demos dengan menggunakan line scripting
*Line 20: mencetak kata File list: dalam tipe string
*Line 21: mencetak suatu simbol dalam tipe string
*Line 23: Jika file tersebut masih terdapat pada folder W01-demos maka 
*nama file tersebut akan diprint
*/
