#!/bin/bash
# REV05: Mon Feb 26 21:39:10 WIB 2018
# START: Mon Sep  5 14:34:41 WIB 2016

# R: Just run "bash a06-loop 11 22 33 44"

# Copyright (C) 2016-2018 http://RahmatM.Samik-Ibrahim.vLSM.org/
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

PREFIX="^#.R:"
RESULT=`grep $PREFIX $0`
clear
if [[ $RESULT ]] ; then
   printf "\n[%11s]: %s\n" "`cut -c 1-11 <<< $0`" "$RESULT"
fi
echo ""; 

echo "============="
echo 'Loop with [*]'
for ii in "$*"
do
   echo $ii
done

echo "=============="
echo 'Loop with [@]'
for ii in "$@"
do
   echo $ii
done
exit 0

/*
* Sun Jun 24 2018
* Notes by M Ikhsan Kurniawan 
* Line 13: variable RESULT akan menampung setiap nama
* file yang ada di dalam folder W01-demos dengan 
* menggunakan line scripting
* Line 22-25: mencetak kata didalam file dengan jumlah 
* baris sesuai dengan jumlah loop
* Line 29-32: mencetak kata didalam file dalam satu baris
*/
