#!/bin/bash
# REV04: Mon Feb 12 19:48:55 WIB 2018
# START: Mon Sep  5 14:38:26 WIB 2016

# R: Just run "bash a07-tester"

# Copyright (C) 2016-2018 http://RahmatM.Samik-Ibrahim.vLSM.org/
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


PREFIX="^#.R:"
RESULT=`grep $PREFIX $0`
clear
if [[ $RESULT ]] ; then
   printf "\n[%11s]: %s\n" "`cut -c 1-11 <<< $0`" "$RESULT"
fi
echo ""; 

for II in ZA-thisfile.tx ZB-SOURCE NOTHING
do
   echo "================================"
   [ -f $II ] && echo "[$II] is a file"
   [ -f $II ] || echo "[$II] is NOT a file"

   if [ -d $II ] 
      then echo "[$II] is a directory"
   else 
      echo "[$II] is NOT a directory"
   fi
done
echo "================================"

exit

/*
* Sun Jun 24 2018
* Notes by M Ikhsan Kurniawan
* Line 14: variable RESULT akan menampung setiap
* nama file yang ada di dalam folder W01-demos
* dengan menggunakan line scripting
* Line 24: jika $II adalah ada dan regular file 
* maka echo "[$II] is a file
* Line 25: jika $II tidak ada atau bukan regular
* file maka echo "[$II] is NOT a file"
* Line 27-28: jika $II ada dan adalah directory
* maka echo "[$II] is a directory"
* Line 29-30: jika $II tidak ada atau bukan directory
* maka echo "[$II] is NOT a directory"
*/
