# (c) 2016-2018 Rahmat M. Samik-Ibrahim
# REV02 Fri Jun 29 02:08:39 WIB 2018
# START Fri Jan 01 00:00:00 WIB 2016
# This is a free Makefile configuration.
# Just run:
# % make

ALL:	c-program-example

c-program-example: c-program-example.c
	gcc -o c-program-example c-program-example.c

clean:
	rm -f c-program-example


#
# Fri Jun 29 20:00:00 WIB 2018
# Notes by Rian Pramudia Salasa
#
# Line 8
# ALL: consist of default targets to compile if you run just 'make'
# command or 'make ALL' without specific target.
#
# Line 11
# command gcc -o will compile file c-program-example.c into
# c-program-example.
#
# Line 13-14
# When you run 'make clean', make program will run command inside
# 'clean:' which is rm -f c-program-example. This will remove
# (with -f = force) file c-program-example.
