# (c) 2016-2018 Rahmat M. Samik-Ibrahim
# REV02 Fri Jun 29 02:08:39 WIB 2018
# START Fri Jan 01 00:00:00 WIB 2016
# This is a free Makefile configuration.
# Just run:
# % make

ALL:	c-program-example

c-program-example: c-program-example.c
	gcc -o c-program-example c-program-example.c

clean:
	rm -f c-program-example


#
# Fri Jun 29 02:08:56 WIB 2018
# Notes by .....
#
#
